<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7I28866" name="com.adactin.Testcases.TestCase104" tests="1" failures="1" timestamp="22 Jul 2016 10:18:41 GMT" time="3.669" errors="0">
  <testcase name="ValidationOfData" time="3.669" classname="com.adactin.Testcases.TestCase104">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Total Price calculated is not proper.Actual Price:AUD $ 685 Expected Price:AUD $675 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Total Price calculated is not proper.Actual Price:AUD $ 685 Expected Price:AUD $675 expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.adactin.Testcases.TestCase104.ValidationOfData(TestCase104.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.TestNG.privateMain(TestNG.java:1405)
	at org.testng.TestNG.main(TestNG.java:1374)
]]>
    </failure>
  </testcase> <!-- ValidationOfData -->
</testsuite> <!-- com.adactin.Testcases.TestCase104 -->
